export const data = [
  {
    key: '1',
    name: 'Innovatech Solutions',
    voucherType: 'Flat Amount',
    numberOfVouchers: 456,
    status: 'Active',
  },
  {
    key: '2',
    name: 'Consulting Partners Group',
    voucherType: 'Percentage',
    numberOfVouchers: 789,
    status: 'Scheduled',
  },
  {
    key: '3',
    name: 'Tech Solutions',
    voucherType: 'Flat Amount',
    numberOfVouchers: 123,
    status: 'Active',
  },
  {
    key: '4',
    name: 'Digital Dynamics',
    voucherType: 'Percentage',
    numberOfVouchers: 325,
    status: 'Active',
  },
  {
    key: '5',
    name: 'Global Marketing Inc',
    voucherType: 'Flat Amount',
    numberOfVouchers: 567,
    status: 'Scheduled',
  },
  {
    key: '6',
    name: 'EcoSmart Innovations',
    voucherType: 'Percentage',
    numberOfVouchers: 214,
    status: 'Active',
  },
  {
    key: '7',
    name: 'Precision Partners',
    voucherType: 'Flat Amount',
    numberOfVouchers: 378,
    status: 'Active',
  },
  {
    key: '8',
    name: 'NextGen Services',
    voucherType: 'Percentage',
    numberOfVouchers: 492,
    status: 'Scheduled',
  },
  {
    key: '9',
    name: 'Apex Analytics',
    voucherType: 'Flat Amount',
    numberOfVouchers: 631,
    status: 'Active',
  },
  {
    key: '10',
    name: 'Innovatech Solutions',
    voucherType: 'Percentage',
    numberOfVouchers: 285,
    status: 'Scheduled',
  },
];
