export const FormConfig: CampaignFieldProps[] = [
  {
    type: 'input',
    label: 'Campaign Name',
    name: 'campaignName',
    placeholder: 'Enter campaign name',
    rules: [{ required: true, message: 'Required' }],
    section: 'generalDetails',
  },
  {
    type: 'input',
    label: 'Total Number of vouchers',
    name: 'totalVouchers',
    placeholder: 'Enter number of vouchers',
    rules: [{ required: true, message: 'Required' }],
    section: 'voucherDetails',
  },
  {
    type: 'select',
    label: 'Voucher Type',
    name: 'voucherType',
    placeholder: 'Select voucher type',
    options: [
      { value: 'percentage', label: 'Percentage' },
      { value: 'fixedAmount', label: 'Fixed Amount' },
    ],
    rules: [{ required: true, message: 'Required' }],
    section: 'voucherDetails',
  },
  {
    type: 'input',
    label: 'Fixed Amount',
    name: 'amount',
    placeholder: 'Enter fixed amount',
    rules: [{ required: true, message: 'Required' }],
    section: 'voucherDetails',
    dependsOn: 'voucherType',
    showWhen: 'fixedAmount',
  },
  {
    type: 'input',
    label: 'Discount Percentage',
    name: 'discountPercentage',
    placeholder: 'Enter discount percentage',
    rules: [{ required: true, message: 'Required' }],
    section: 'voucherDetails',
    dependsOn: 'voucherType',
    showWhen: 'percentage',
  },
  {
    type: 'input',
    label: 'Maximum amount that can be discounted',
    name: 'maxDiscountAmount',
    placeholder: 'Enter maximum discount amount',
    rules: [{ required: true, message: 'Required' }],
    section: 'voucherDetails',
    dependsOn: 'voucherType',
    showWhen: 'percentage',
  },
  {
    type: 'select',
    label: 'Applied Merchants',
    name: 'appliedMerchants',
    placeholder: 'Select applied merchants',
    options: [
      { value: 'merchant01', label: 'Merchant 01' },
      { value: 'merchant02', label: 'Merchant 02' },
    ],
    rules: [{ required: true, message: 'Required' }],
    section: 'campaignDetails',
  },
  {
    type: 'multiSelect',
    label: 'Applied Products',
    name: 'appliedProducts',
    placeholder: 'Select applied products',
    options: [
      { value: 'product01', label: 'Product 01' },
      { value: 'product02', label: 'Product 02' },
      { value: 'product03', label: 'Product 03' },
      { value: 'product04', label: 'Product 04' },
      { value: 'product05', label: 'Product 05' },
      { value: 'product06', label: 'Product 06' },
      { value: 'product07', label: 'Product 07' },
      { value: 'product08', label: 'Product 08' },
      { value: 'product09', label: 'Product 08' },
      { value: 'product10', label: 'Product 10' },
      { value: 'product11', label: 'Product 11' },
    ],
    rules: [{ required: true, message: 'Required' }],
    section: 'campaignDetails',
  },
  {
    type: 'radio',
    label: '',
    name: 'scheduleCampaign',
    options: [
      { value: 'schedule', label: 'Schedule the campaign' },
      { value: 'publish', label: 'Publish right away' },
    ],
    rules: [{ required: true, message: 'Required' }],
    section: 'scheduleCampaign',
  },
  {
    type: 'date',
    label: 'Campaign Start Date & Time',
    name: 'campaignStartDate',
    placeholder: 'Select start date & time',
    rules: [{ required: true, message: 'Required' }],
    section: 'scheduleCampaignDate',
  },
  {
    type: 'date',
    label: 'Campaign End Date & Time',
    name: 'campaignEndDate',
    placeholder: 'Select end date & time',
    rules: [{ required: true, message: 'Required' }],
    section: 'scheduleCampaignDate',
  },
];
