version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: deels
      POSTGRES_PASSWORD: deels
      POSTGRES_DB: deels
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: